### ISSUE TITLE
Rename repo to "website"

### ISSUE THREAD

**Issue by jasonkuhrt** [haskell-learning-group/hlg.io#3]
@neongreen Ok?

**Comment by neongreen** [comment]
Okay (`site` might also work). Before you do it, though, I want you to know the original rationale for naming it `hlg.io`. 
- When someone forks the repo, they will have `hlg.io` in their repositories on Github and not something generic like `website`.
- When the repo is named in a unique way, `git clone` automatically results in a good name for the folder (`~/code/site` isn't a good name), and I suspect that lots of people won't think of doing a named git clone – potentially leading to confusion.

So, you can do it but keep points above in mind.

**Comment by jasonkuhrt** [comment]
I think those are compelling points! Lets stick with it then.
